### ISSUE TITLE
App startet mit Fehler

### ISSUE THREAD

**Issue by Mehyar-ALS** [DoganGuendogdu/Karteikarten#1]
Wenn ich die App starte, kriege ich die Fehler Meldung. 

> Modul 'tkinter' wird importiert
> install: missing destination file operand after 'python3-tk'
> Try 'install --help' for more information.
> 
> Wilkommen zum Lernprogramm
> Bitte beachten Sie die Gross,- und Kleinschreibung
> Bitte waehlen Sie ihre Csv-Datei aus

Ich habe die App wie in der Doku mit `python3 main.py ` gestartet.

Müss ich schon bevor ien CSV Datei haben? Gibt's kein CSV Datei als Beispiel im Code?

**Comment by DoganGuendogdu** [comment]
Entschuldige erstmal für die späte Antwort.
Zu deinem Problem: Auf welchem OS hast du das Programm ausgeführt? 

Für die CSV-Datei bist du selbst als User verantwortlich. Es geht schlussendlich ja darum, dass der User eine Datei einliest, 
in der seine **eigenen** Karteikarten stehen (Fragen und Antworten)

**Comment by DoganGuendogdu** [comment]
Ich habe es in einer VM ausgeführt und den Fehler erkannt.
Der Fehler entsteht durch das falsche Installieren des 'tk-module'.

Lösung:
``` 
 sudo apt-get install python3-tk

```
Die README ist dementsprechend aktualisiert worden.

**Comment by Mehyar-ALS** [comment]
Alles klar, danke dir.
